function replaceSpec(Texte){
  var TabSpec = {"à":"a","á":"a","â":"a","ã":"a","ä":"a","å":"a","ò":"o","ó":"o","ô":"o","õ":"o","ö":"o","ø":"o","è":"e","é":"e","ê":"e","ë":"e","ç":"c","ì":"i","í":"i","î":"i","ï":"i","ù":"u","ú":"u","û":"u","ü":"u","ÿ":"y","ñ":"n","-":" ","_":" "}; 
	var reg=/[àáäâèéêëçìíîïòóôõöøùúûüÿñ_-]/gi; 
	return Texte.replace(reg,function(){ return TabSpec[arguments[0].toLowerCase()];}).toLowerCase();
}

function replaceByGroup(choice){
  if (choice == "Front de gauche / Parti communiste")
    nbGroup = 1;
  else if (choice == "Europe Écologie / Génération.s, le mouvement")
    nbGroup = 2;
  else if (choice == "Parti socialiste / Parti radical")
    nbGroup = 3;
  else if (choice == "UDI / Modem / En Marche")
    nbGroup = 4;
  else if (choice == "Les Républicains et apparentés")
    nbGroup = 5;
  else if (choice == "Rassemblement national / Les Patriotes / Debout la France / Apparentés")
    nbGroup =  6;
  else
    nbGroup = 7;
  return nbGroup
}


function calculateMostAdapted(answers) {
  var mostImportantScore = [-1, -1]
  var same_gender = []
  var same_firstname = []
  var similar_firstname = []
  var same_circo = []
  var same_birthdate = []
  var birthdate = []
  var same_party = []

  for(var i = 0; i < liste_dep.length; i++) {
    var result = 1
    // On s'occupe du genre 
    if (liste_dep[i].gender == answers[0].substring(0,1).toUpperCase()) {
      same_gender.push(liste_dep[i].name);
      result = result + 1200;
    }
    // On s'occupe du prénom
    if (replaceSpec(liste_dep[i].first_name).indexOf(replaceSpec(answers[1])) !== -1) {
      if (replaceSpec(liste_dep[i].first_name) == replaceSpec(answers[1])){
        same_firstname.push(liste_dep[i].name)
        result = result + 200
      }
      else {
        similar_firstname.push(liste_dep[i].name)
        result = result + 100
      }  
    }
    // On s'occupe de la circonscription
    if (liste_dep[i].circo == answers[2]) {
      same_circo.push(liste_dep[i].name);
      result = result + 1200;
    }
    // On s'occupe de l'année de naissance
    if (Number(liste_dep[i].date_birth.slice(-4)) == Number(answers[3])) {
      same_birthdate.push(liste_dep[i].name);
      result = result + 1000;
    }
    else {
      difference = Math.abs(Number(answers[3]) - Number(liste_dep[i].date_birth.slice(-4)))
      birthdate.push([liste_dep[i].name, difference, Number(liste_dep[i].date_birth.slice(-4))]);
      result = result + 1000/difference;
    }
    // On s'occupe des affinités politiques
    if (replaceByGroup(answers[4]) == liste_dep[i].national_party_grp) {
      same_party.push(liste_dep[i].name);
      result = result + 10000;
    }
    else if (Math.abs(replaceByGroup(answers[4]) - liste_dep[i].national_party_grp) == 1) {
      same_party.push(liste_dep[i].name);
      result = result + 6000;
    }
    if (result > mostImportantScore[1])
      mostImportantScore = [liste_dep[i].num, result]
  }
  tab = [mostImportantScore[0], same_gender, same_firstname, same_circo, same_party]
  return(tab)
}

var vm = new Vue({
  el: '.app',
  data: function () {
    var now = new Date();
    var days = ['dimanche', 'lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi']
    var months = ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre']
    return  {
      intro: "Et il nous reste seulement quelque mois avant d'élire nos députés européens, souvent décriés pour leur manque de représentativité. D'ailleurs, X% des Français affirment ne pas leur faire confiance et X% ne pas se sentir représentés par eux. Nous vous proposons d'explorer la galaxie des députés européens élus en France, pour trouver celui qui vous ressemble le plus. Nous avons déterminé et pondéré plusieurs critères. Maintenant, à vous de jouer !",
      now: now,
      day: days[now.getDay()],
      month: months[now.getMonth()]
    };
  }
});

var app = new Vue({
  el: '#app',
  data: {
    quiz: quiz, 
    current: 0, 
    answers: []
  },
  computed: {
    step: function step () {
      return this.quiz[this.current];
    }
  },
  methods: {
    submitButton: function submitButton (answer) {
      this.answers.push(answer)
      this.current++
      if (this.current == this.quiz.length){
        tab = calculateMostAdapted(this.answers)
        num_match = tab[0]
        this.same_firstname = tab[2]
        this.lector_name = this.answers[1]
        this.lector_gender = this.answers[0]
        this.match_name = liste_dep[num_match].name
        this.match_party = liste_dep[num_match].national_party
        this.match_circo = liste_dep[num_match].circo
        this.match_gender = liste_dep[num_match].gender
        this.match_date_birth = liste_dep[num_match].date_birth
        this.match_place_birth = liste_dep[num_match].place_birth
        this.match_eurodep_depuis = liste_dep[num_match].eurodep_depuis
      }
    },
    submitText: function submitText () {
      var answer = this.$refs.textInput.value;
      this.answers.push(answer)
      this.current++ 
    },
    submitNumber: function submitNumber() {
      var answer = this.$refs.nbInput.value;
      this.answers.push(answer)
      this.current++
    }
  }
});


var liste_dep = [
  {
    "num": 0,
    "id": 124765,
    "name": "Joëlle MÉLIN",
    "first_name": "Joëlle",
    "last_name": "MÉLIN",
    "gender": "F",
    "date_birth": "26 mars 1950",
    "place_birth": "Versailles",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Sud-Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "BLEU MARINE OUI A LA FRANCE NON A BRUXELLES (LFN)",
    "resultat_liste": "24,71",
    "nb_voix_liste": 726797,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124765/JOELLE_MELIN_home.html",
    "lien_site": "http://joellemelin.com/",
    "lien_twitter": "https://twitter.com/JoelleMelinFN",
    "certifié": "Non",
    "followers": 4167,
    "result": 0
  },
  {
    "num": 1,
    "id": 189065,
    "name": "France JAMET",
    "first_name": "France",
    "last_name": "JAMET",
    "gender": "F",
    "date_birth": "5 février 1961",
    "place_birth": "Paris",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Sud-Ouest",
    "eurodep_depuis": 2017,
    "longevity": 2,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "OUI",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "BLEU MARINE OUI A LA FRANCE NON A BRUXELLES (LFN)",
    "resultat_liste": 726797,
    "nb_voix_liste": "24,71",
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/189065/FRANCE_JAMET_home.html",
    "lien_site": "https://francejamet.com/",
    "lien_twitter": "https://twitter.com/FranceJamet",
    "certifié": "Non",
    "followers": 4074,
    "result": 0
  },
  {
    "num": 2,
    "id": 191510,
    "name": "Jacques COLOMBIER",
    "first_name": "Jacques",
    "last_name": "COLOMBIER",
    "gender": "H",
    "date_birth": "17 février 1952",
    "place_birth": "Trèves",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Sud-Ouest",
    "eurodep_depuis": 2018,
    "longevity": 1,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "OUI",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "BLEU MARINE OUI A LA FRANCE NON A BRUXELLES (LFN)",
    "resultat_liste": 726797,
    "nb_voix_liste": "24,71",
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/191510/JACQUES_COLOMBIER_home.html",
    "lien_site": "Aucun",
    "lien_twitter": "https://twitter.com/JColombierFN",
    "certifié": "Non",
    "followers": 2918,
    "result": 0
  },
  {
    "num": 3,
    "id": 28166,
    "name": "Vincent PEILLON",
    "first_name": "Vincent",
    "last_name": "PEILLON",
    "gender": "H",
    "date_birth": "7 juillet 1960",
    "place_birth": "Suresnes",
    "national_party": "Parti socialiste",
    "national_party_grp": 3,
    "circo": "Sud-Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "2004-2012",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "11,88",
    "nb_voix_liste": 394114,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/28166/VINCENT_PEILLON_home.html",
    "lien_site": "Aucun",
    "lien_twitter": "https://twitter.com/Vincent_Peillon",
    "certifié": "Oui",
    "followers": 61061,
    "result": 0
  },
  {
    "num": 4,
    "id": 24505,
    "name": "Emmanuel MAUREL",
    "first_name": "Emmanuel",
    "last_name": "MAUREL",
    "gender": "H",
    "date_birth": "10 mai 1973",
    "place_birth": "Epinay",
    "national_party": "Parti socialiste",
    "national_party_grp": 3,
    "circo": "Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "15,62",
    "nb_voix_liste": 425722,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/24505/EMMANUEL_MAUREL_home.html",
    "lien_site": "https://emmanuelmaurel.eu/",
    "lien_twitter": "https://twitter.com/emmanuelmaurel",
    "certifié": "Oui",
    "followers": 13792,
    "result": 0
  },
  {
    "num": 5,
    "id": 124744,
    "name": "Guillaume BALAS",
    "first_name": "Guillaume",
    "last_name": "BALAS",
    "gender": "H",
    "date_birth": "30 août 1972",
    "place_birth": "Rillieux-la-Pape",
    "national_party": "Génération.s, le mouvement",
    "national_party_grp": 2,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "14,28",
    "nb_voix_liste": 437678,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124744/GUILLAUME_BALAS_home.html",
    "lien_site": "http://www.guillaumebalas.eu/",
    "lien_twitter": "https://twitter.com/BalasGuillaume",
    "certifié": "Oui",
    "followers": 12181,
    "result": 0
  },
  {
    "num": 6,
    "id": 114279,
    "name": "Isabelle THOMAS",
    "first_name": "Isabelle",
    "last_name": "THOMAS",
    "gender": "F",
    "date_birth": "26 novembre 1961",
    "place_birth": "Blanc-Mesnil",
    "national_party": "Génération.s, le mouvement",
    "national_party_grp": 2,
    "circo": "Ouest",
    "eurodep_depuis": 2012,
    "longevity": 7,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "15,62",
    "nb_voix_liste": 425722,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/114279/ISABELLE_THOMAS_home.html",
    "lien_site": "http://isabelle-thomas.fr",
    "lien_twitter": "https://twitter.com/Isabel_thomasEU",
    "certifié": "Oui",
    "followers": 8038,
    "result": 0
  },
  {
    "num": 7,
    "id": 1985,
    "name": "Pervenche BERÈS",
    "first_name": "Pervenche",
    "last_name": "BERÈS",
    "gender": "F",
    "date_birth": "10 mars 1957",
    "place_birth": "Neully-sur-Seine",
    "national_party": "Parti socialiste",
    "national_party_grp": 3,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 1994,
    "longevity": 25,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "14,28",
    "nb_voix_liste": 437678,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/1985/PERVENCHE_BERES_home.html",
    "lien_site": "https://www.pervencheberes.fr/",
    "lien_twitter": "https://twitter.com/PervencheBeres",
    "certifié": "Oui",
    "followers": 7532,
    "result": 0
  },
  {
    "num": 8,
    "id": 96952,
    "name": "Sylvie GUILLAUME",
    "first_name": "Sylvie",
    "last_name": "GUILLAUME",
    "gender": "F",
    "date_birth": "11 juin 1962",
    "place_birth": "Antony",
    "national_party": "Parti socialiste",
    "national_party_grp": 3,
    "circo": "Sud-Est",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "11,88",
    "nb_voix_liste": 394114,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96952/SYLVIE_GUILLAUME_home.html",
    "lien_site": "http://www.sylvieguillaume.eu",
    "lien_twitter": "http://twitter.com/sylvieguillaume",
    "certifié": "Oui",
    "followers": 7474,
    "result": 0
  },
  {
    "num": 9,
    "id": 96948,
    "name": "Gilles PARGNEAUX",
    "first_name": "Gilles",
    "last_name": "PARGNEAUX",
    "gender": "H",
    "date_birth": "24 mars 1957",
    "place_birth": "Harcigny",
    "national_party": "Parti socialiste",
    "national_party_grp": 3,
    "circo": "Nord-Ouest",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "11,78",
    "nb_voix_liste": 320250,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96948/GILLES_PARGNEAUX_home.html",
    "lien_site": "http://gillespargneaux.typepad.fr/",
    "lien_twitter": "https://twitter.com/gillespargneaux",
    "certifié": "Oui",
    "followers": 5782,
    "result": 0
  },
  {
    "num": 10,
    "id": 124947,
    "name": "Edouard MARTIN",
    "first_name": "Edouard",
    "last_name": "MARTIN",
    "gender": "H",
    "date_birth": "15 juin 1963",
    "place_birth": "Padul (ES)",
    "national_party": "Parti socialiste",
    "national_party_grp": 3,
    "circo": "Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "13,24",
    "nb_voix_liste": 321563,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124947/EDOUARD_MARTIN_home.html",
    "lien_site": "http://www.edouardmartin.eu/",
    "lien_twitter": "https://twitter.com/edouardmartineu",
    "certifié": "Oui",
    "followers": 5346,
    "result": 0
  },
  {
    "num": 11,
    "id": 124287,
    "name": "Christine REVAULT D'ALLONNES BONNEFOY",
    "first_name": "Christine",
    "last_name": "REVAULT D'ALLONNES BONNEFOY",
    "gender": "F",
    "date_birth": "10 novembre 1971",
    "place_birth": "Châteauroux",
    "national_party": "Parti socialiste",
    "national_party_grp": 3,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "14,28",
    "nb_voix_liste": 437678,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124287/CHRISTINE_REVAULT+D%27ALLONNES+BONNEFOY_home.html",
    "lien_site": "https://crevaultdallonnesbonnefoy.eu/",
    "lien_twitter": "https://twitter.com/cdallonnes",
    "certifié": "Oui",
    "followers": 3978,
    "result": 0
  },
  {
    "num": 12,
    "id": 103845,
    "name": "Virginie ROZIÈRE",
    "first_name": "Virginie",
    "last_name": "ROZIÈRE",
    "gender": "F",
    "date_birth": "18 juin 1976",
    "place_birth": "Montpelllier",
    "national_party": "Les radicaux de Gauche",
    "national_party_grp": 3,
    "circo": "Sud-Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "15,73",
    "nb_voix_liste": 462737,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/103845/VIRGINIE_ROZIERE_home.html",
    "lien_site": "http://www.virginieroziere.eu/",
    "lien_twitter": "https://twitter.com/Vroziere",
    "certifié": "Oui",
    "followers": 3561,
    "result": 0
  },
  {
    "num": 13,
    "id": 193080,
    "name": "Karine GLOANEC MAURIN",
    "first_name": "Karine",
    "last_name": "GLOANEC MAURIN",
    "gender": "F",
    "date_birth": "11 janvier 1958",
    "place_birth": "Châteaubriant",
    "national_party": "Parti socialiste",
    "national_party_grp": 3,
    "circo": "Massif-Central Centre",
    "eurodep_depuis": 2018,
    "longevity": 1,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "OUI",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": 233079,
    "nb_voix_liste": "15,82",
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/193080/KARINE_GLOANEC+MAURIN_home.html",
    "lien_site": "http://www.karinegloanecmaurin.eu",
    "lien_twitter": "https://twitter.com/KGloanecMaurin",
    "certifié": "Non",
    "followers": 947,
    "result": 0
  },
  {
    "num": 14,
    "id": 113892,
    "name": "Eric ANDRIEU",
    "first_name": "Eric",
    "last_name": "ANDRIEU",
    "gender": "H",
    "date_birth": "14 avril 1960",
    "place_birth": "Narbonne",
    "national_party": "Parti socialiste",
    "national_party_grp": 3,
    "circo": "Sud-Ouest",
    "eurodep_depuis": 2012,
    "longevity": 7,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "15,73",
    "nb_voix_liste": 462737,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/113892/ERIC_ANDRIEU_home.html",
    "lien_site": "http://www.eric-andrieu.eu/",
    "lien_twitter": "https://twitter.com/Eric_Andrieu",
    "certifié": "Non",
    "followers": 375,
    "result": 0
  },
  {
    "num": 15,
    "id": 124725,
    "name": "Louis-Joseph MANSCOUR",
    "first_name": "Louis-Joseph",
    "last_name": "MANSCOUR",
    "gender": "H",
    "date_birth": "20 mars 1945",
    "place_birth": "La Trinité (Martinique)",
    "national_party": "Parti socialiste",
    "national_party_grp": 3,
    "circo": "Outre-Mer",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe de l'Alliance Progressiste des Socialistes et Démocrates au Parlement européen",
    "liste_regionale": "CHOISIR NOTRE EUROPE (LUG)",
    "resultat_liste": "19,36",
    "nb_voix_liste": 55214,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124725/LOUIS-JOSEPH_MANSCOUR_home.html",
    "lien_site": "http://louis-josephmanscour.fr/",
    "lien_twitter": "None",
    "certifié": "None",
    "followers": 0,
    "result": 0
  },
  {
    "num": 16,
    "id": 96744,
    "name": "José BOVÉ",
    "first_name": "José",
    "last_name": "BOVÉ",
    "gender": "H",
    "date_birth": "11 juin 1953",
    "place_birth": "Talence",
    "national_party": "Europe Écologie",
    "national_party_grp": 2,
    "circo": "Sud-Ouest",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe des Verts/Alliance libre européenne",
    "liste_regionale": "EUROPE ECOLOGIE (LVEC)",
    "resultat_liste": "11,48",
    "nb_voix_liste": 337554,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96744/JOSE_BOVE_home.html",
    "lien_site": "http://jose-bove.eu/?lang=fr",
    "lien_twitter": "https://twitter.com/josebove",
    "certifié": "Oui",
    "followers": 58316,
    "result": 0
  },
  {
    "num": 17,
    "id": 96743,
    "name": "Michèle RIVASI",
    "first_name": "Michèle",
    "last_name": "RIVASI",
    "gender": "F",
    "date_birth": "9 février 1953",
    "place_birth": "Montélimar",
    "national_party": "Europe Écologie",
    "national_party_grp": 2,
    "circo": "Sud-Est",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe des Verts/Alliance libre européenne",
    "liste_regionale": "EUROPE ECOLOGIE (LVEC)",
    "resultat_liste": "9,32",
    "nb_voix_liste": 309168,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96743/MICHELE_RIVASI_home.html",
    "lien_site": "http://www.michele-rivasi.eu/",
    "lien_twitter": "https://twitter.com/MicheleRivasi",
    "certifié": "Oui",
    "followers": 20832,
    "result": 0
  },
  {
    "num": 18,
    "id": 188721,
    "name": "Marie-Pierre VIEU",
    "first_name": "Marie-Pierre",
    "last_name": "VIEU",
    "gender": "F",
    "date_birth": "1 février 1967",
    "place_birth": "Tarbes",
    "national_party": "Front de Gauche",
    "national_party_grp": 1,
    "circo": "Sud-Ouest",
    "eurodep_depuis": 2017,
    "longevity": 2,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "OUI",
    "eurogroup": "Groupe confédéral de la Gauche unitaire européenne/Gauche verte nordique",
    "liste_regionale": "FRONT DE GAUCHE (LFG)",
    "resultat_liste": 252197,
    "nb_voix_liste": "8,57",
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/188721/MARIE-PIERRE_VIEU_home.html",
    "lien_site": "http://mpvieu.canalblog.com/",
    "lien_twitter": "https://twitter.com/mariepierrevieu",
    "certifié": "Non",
    "followers": 3918,
    "result": 0
  },
  {
    "num": 19,
    "id": 1023,
    "name": "Jean-Marie LE PEN",
    "first_name": "Jean-Marie",
    "last_name": "LE PEN",
    "gender": "H",
    "date_birth": "20 juin 1928",
    "place_birth": "La Trinité-sur-Mer (Morbihan)",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Sud-Est",
    "eurodep_depuis": 2004,
    "longevity": 15,
    "mandats_parl_eur": "1984-2003",
    "succession_cours_mandat": "NON",
    "eurogroup": "Non-inscrits",
    "liste_regionale": "FRONT NATIONAL (LFN)",
    "resultat_liste": "28,18",
    "nb_voix_liste": 935182,
    "nb_elus_liste": 5,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/1023/JEAN-MARIE_LE+PEN_home.html",
    "lien_site": "http://www.jeanmarielepen.com/",
    "lien_twitter": "https://twitter.com/brunogollnisch",
    "certifié": "Oui",
    "followers": 27987,
    "result": 0
  },
  {
    "num": 20,
    "id": 1164,
    "name": "Bruno GOLLNISCH",
    "first_name": "Bruno",
    "last_name": "GOLLNISCH",
    "gender": "H",
    "date_birth": "28 janvier 1950",
    "place_birth": "Neuilly-sur-Seine",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Sud-Est",
    "eurodep_depuis": 1989,
    "longevity": 30,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Non-inscrits",
    "liste_regionale": "FRONT NATIONAL (LFN)",
    "resultat_liste": "28,18",
    "nb_voix_liste": 935182,
    "nb_elus_liste": 5,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/1164/BRUNO_GOLLNISCH_home.html",
    "lien_site": "http://www.gollnisch.com",
    "lien_twitter": "http://twitter.com/brunogollnisch",
    "certifié": "Oui",
    "followers": 27987,
    "result": 0
  },
  {
    "num": 21,
    "id": 124748,
    "name": "Marie-Christine ARNAUTU",
    "first_name": "Marie-Christine",
    "last_name": "ARNAUTU",
    "gender": "F",
    "date_birth": "19 octobre 1952",
    "place_birth": "Paris",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Sud-Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "FRONT NATIONAL (LFN)",
    "resultat_liste": "28,18",
    "nb_voix_liste": 935182,
    "nb_elus_liste": 5,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124748/MARIE-CHRISTINE_ARNAUTU_home.html",
    "lien_site": "http://arnautu.fr/",
    "lien_twitter": "https://twitter.com/MCArnautu",
    "certifié": "Oui",
    "followers": 11299,
    "result": 0
  },
  {
    "num": 22,
    "id": 124750,
    "name": "Mireille D'ORNANO",
    "first_name": "Mireille",
    "last_name": "D'ORNANO",
    "gender": "F",
    "date_birth": "29 juin 1951",
    "place_birth": "",
    "national_party": "Les Patriotes",
    "national_party_grp": 6,
    "circo": "Sud-Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe de la liberté et de la démocratie directe",
    "liste_regionale": "FRONT NATIONAL (LFN)",
    "resultat_liste": "28,18",
    "nb_voix_liste": 935182,
    "nb_elus_liste": 5,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124750/MIREILLE_D%27ORNANO_home.html",
    "lien_site": "http://mireilledornano.eu/",
    "lien_twitter": "https://twitter.com/MireilledOrnano",
    "certifié": "Oui",
    "followers": 4564,
    "result": 0
  },
  {
    "num": 23,
    "id": 124751,
    "name": "Dominique MARTIN",
    "first_name": "Dominique",
    "last_name": "MARTIN",
    "gender": "H",
    "date_birth": "1 octobre 1961",
    "place_birth": "Scionzier",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Sud-Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "FRONT NATIONAL (LFN)",
    "resultat_liste": "28,18",
    "nb_voix_liste": 935182,
    "nb_elus_liste": 5,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124751/DOMINIQUE_MARTIN_home.html",
    "lien_site": "http://dominique-martin.com/",
    "lien_twitter": "https://twitter.com/DMartinFN",
    "certifié": "Oui",
    "followers": 2710,
    "result": 0
  },
  {
    "num": 24,
    "id": 96858,
    "name": "Marie-Christine VERGIAT",
    "first_name": "Marie-Christine",
    "last_name": "VERGIAT",
    "gender": "F",
    "date_birth": "23 septembre 1956",
    "place_birth": "Roanne",
    "national_party": "Front de Gauche",
    "national_party_grp": 1,
    "circo": "Sud-Est",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe confédéral de la Gauche unitaire européenne/Gauche verte nordique",
    "liste_regionale": "L'EUROPE DE LA FINANCE, ÇA SUFFIT ! PLACE AU PEUPLE ! (LFG)",
    "resultat_liste": "5,96",
    "nb_voix_liste": 197754,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96858/MARIE-CHRISTINE_VERGIAT_home.html",
    "lien_site": "http://www.eurocitoyenne.fr/",
    "lien_twitter": "http://twitter.com/MCVergiat",
    "certifié": "Non",
    "followers": 4579,
    "result": 0
  },
  {
    "num": 25,
    "id": 30482,
    "name": "Younous OMARJEE",
    "first_name": "Younous",
    "last_name": "OMARJEE",
    "gender": "H",
    "date_birth": "30 septembre 1969",
    "place_birth": "Saint-Denis (Réunion)",
    "national_party": "L'union pour les Outremer",
    "national_party_grp": 1,
    "circo": "Outre-Mer",
    "eurodep_depuis": 2012,
    "longevity": 7,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe confédéral de la Gauche unitaire européenne/Gauche verte nordique",
    "liste_regionale": "L'UNION POUR LES OUTREMER (LDVG)",
    "resultat_liste": "18,23",
    "nb_voix_liste": 52017,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/30482/YOUNOUS_OMARJEE_home.html",
    "lien_site": "http://younousomarjee.eu/",
    "lien_twitter": "https://twitter.com/younousomarjee",
    "certifié": "Oui",
    "followers": 5468,
    "result": 0
  },
  {
    "num": 26,
    "id": 110977,
    "name": "Florian PHILIPPOT",
    "first_name": "Florian",
    "last_name": "PHILIPPOT",
    "gender": "H",
    "date_birth": "24 octobre 1981",
    "place_birth": "Croix",
    "national_party": "Les Patriotes",
    "national_party_grp": 6,
    "circo": "Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe de la liberté et de la démocratie directe",
    "liste_regionale": "LISTE BLEU MARINE - NON A BRUXELLES, OUI A LA FRANCE (LFN)",
    "resultat_liste": "28,98",
    "nb_voix_liste": 703809,
    "nb_elus_liste": 4,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/110977/FLORIAN_PHILIPPOT_home.html",
    "lien_site": "Aucun",
    "lien_twitter": "https://twitter.com/f_philippot",
    "certifié": "Oui",
    "followers": 179861,
    "result": 0
  },
  {
    "num": 27,
    "id": 124752,
    "name": "Aymeric CHAUPRADE",
    "first_name": "Aymeric",
    "last_name": "CHAUPRADE",
    "gender": "H",
    "date_birth": "13 janvier 1969",
    "place_birth": "La Ferté Bernard",
    "national_party": "Les Français Libres",
    "national_party_grp": 6,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe de la liberté et de la démocratie directe",
    "liste_regionale": "LISTE BLEU MARINE - NON A BRUXELLES, OUI A LA FRANCE (LFN)",
    "resultat_liste": 17,
    "nb_voix_liste": 521093,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124752/AYMERIC_CHAUPRADE_home.html",
    "lien_site": "https://www.aymericchauprade.com/",
    "lien_twitter": "https://twitter.com/a_chauprade",
    "certifié": "Oui",
    "followers": 13480,
    "result": 0
  },
  {
    "num": 28,
    "id": 125684,
    "name": "Philippe LOISEAU",
    "first_name": "Philippe",
    "last_name": "LOISEAU",
    "gender": "H",
    "date_birth": "24 novembre 1957",
    "place_birth": "Chartres",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Massif-Central Centre",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "OUI",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "LISTE BLEU MARINE - NON A BRUXELLES, OUI A LA FRANCE (LFN)",
    "resultat_liste": 356098,
    "nb_voix_liste": "24,18",
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/125684/PHILIPPE_LOISEAU_home.html",
    "lien_site": "Aucun",
    "lien_twitter": "https://twitter.com/ph_loiseau",
    "certifié": "Oui",
    "followers": 5425,
    "result": 0
  },
  {
    "num": 29,
    "id": 124761,
    "name": "Bernard MONOT",
    "first_name": "Bernard",
    "last_name": "MONOT",
    "gender": "H",
    "date_birth": "3 juillet 1962",
    "place_birth": "Nice",
    "national_party": "Debout la France",
    "national_party_grp": 6,
    "circo": "Massif-Central Centre",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe de la liberté et de la démocratie directe",
    "liste_regionale": "LISTE BLEU MARINE - NON A BRUXELLES, OUI A LA FRANCE (LFN)",
    "resultat_liste": "24,18",
    "nb_voix_liste": 356098,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124761/BERNARD_MONOT_home.html",
    "lien_site": "http://bernardmonot.com/",
    "lien_twitter": "https://twitter.com/edouardmartinEU",
    "certifié": "Oui",
    "followers": 5346,
    "result": 0
  },
  {
    "num": 30,
    "id": 124770,
    "name": "Jean-François JALKH",
    "first_name": "Jean-François",
    "last_name": "JALKH",
    "gender": "H",
    "date_birth": "23 mai 1957",
    "place_birth": "Tournan-en-Brie",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "LISTE BLEU MARINE - NON A BRUXELLES, OUI A LA FRANCE (LFN)",
    "resultat_liste": "28,98",
    "nb_voix_liste": 703809,
    "nb_elus_liste": 4,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124770/JEAN-FRANCOIS_JALKH_home.html",
    "lien_site": "https://jfjalkh.eu/fr/",
    "lien_twitter": "https://twitter.com/JFJalkh",
    "certifié": "Oui",
    "followers": 4974,
    "result": 0
  },
  {
    "num": 31,
    "id": 124771,
    "name": "Dominique BILDE",
    "first_name": "Dominique",
    "last_name": "BILDE",
    "gender": "F",
    "date_birth": "1 août 1953",
    "place_birth": "Nancy",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "LISTE BLEU MARINE - NON A BRUXELLES, OUI A LA FRANCE (LFN)",
    "resultat_liste": "28,98",
    "nb_voix_liste": 703809,
    "nb_elus_liste": 4,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124771/DOMINIQUE_BILDE_home.html",
    "lien_site": "http://dominiquebilde.eu",
    "lien_twitter": "https://twitter.com/dominiquebilde",
    "certifié": "Oui",
    "followers": 4884,
    "result": 0
  },
  {
    "num": 32,
    "id": 124769,
    "name": "Sophie MONTEL",
    "first_name": "Sophie",
    "last_name": "MONTEL",
    "gender": "F",
    "date_birth": "22 novembre 1969",
    "place_birth": "Montbéliard",
    "national_party": "Les Patriotes",
    "national_party_grp": 6,
    "circo": "Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe de la liberté et de la démocratie directe",
    "liste_regionale": "LISTE BLEU MARINE - NON A BRUXELLES, OUI A LA FRANCE (LFN)",
    "resultat_liste": "28,98",
    "nb_voix_liste": 703809,
    "nb_elus_liste": 4,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124769/SOPHIE_MONTEL_home.html",
    "lien_site": "http://sophiemontel.eu/",
    "lien_twitter": "https://twitter.com/IsabellaDeMonte",
    "certifié": "Non",
    "followers": 3553,
    "result": 0
  },
  {
    "num": 33,
    "id": 124753,
    "name": "Marie-Christine BOUTONNET",
    "first_name": "Marie-Christine",
    "last_name": "BOUTONNET",
    "gender": "F",
    "date_birth": "10 février 1949",
    "place_birth": "Albi",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "LISTE BLEU MARINE - NON A BRUXELLES, OUI A LA FRANCE (LFN)",
    "resultat_liste": 17,
    "nb_voix_liste": 521093,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124753/MARIE-CHRISTINE_BOUTONNET_home.html",
    "lien_site": "http://mc-boutonnet.fr/",
    "lien_twitter": "https://twitter.com/mcboutonnetfn",
    "certifié": "Non",
    "followers": 469,
    "result": 0
  },
  {
    "num": 34,
    "id": 124755,
    "name": "Jean-Luc SCHAFFHAUSER",
    "first_name": "Jean-Luc",
    "last_name": "SCHAFFHAUSER",
    "gender": "H",
    "date_birth": "17 décembre 1955",
    "place_birth": "Cambrai",
    "national_party": "Rassemblement bleu Marine",
    "national_party_grp": 6,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "LISTE BLEU MARINE - NON A BRUXELLES, OUI A LA FRANCE (LFN)",
    "resultat_liste": 17,
    "nb_voix_liste": 521093,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124755/JEAN-LUC_SCHAFFHAUSER_home.html",
    "lien_site": "http://jeanlucschaffhauser.eu",
    "lien_twitter": "https://twitter.com/JLSchaffhauser",
    "certifié": "Non",
    "followers": 460,
    "result": 0
  },
  {
    "num": 35,
    "id": 124738,
    "name": "Gilles LEBRETON",
    "first_name": "Gilles",
    "last_name": "LEBRETON",
    "gender": "H",
    "date_birth": "11 octobre 1958",
    "place_birth": "Brest",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "LISTE BLEU MARINE- NON A BRUXELLES, OUI A LA FRANCE (LFN)",
    "resultat_liste": "19,31",
    "nb_voix_liste": 526019,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124738/GILLES_LEBRETON_home.html",
    "lien_site": "http://gilleslebreton.eu/",
    "lien_twitter": "https://twitter.com/Gilles_Lebreton",
    "certifié": "Oui",
    "followers": 10766,
    "result": 0
  },
  {
    "num": 36,
    "id": 124740,
    "name": "Joëlle BERGERON",
    "first_name": "Joëlle",
    "last_name": "BERGERON",
    "gender": "F",
    "date_birth": "28 juin 1949",
    "place_birth": "Charlieu",
    "national_party": "Sans étiquette",
    "national_party_grp": 7,
    "circo": "Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe de la liberté et de la démocratie directe",
    "liste_regionale": "LISTE BLEU MARINE- NON A BRUXELLES, OUI A LA FRANCE (LFN)",
    "resultat_liste": "19,31",
    "nb_voix_liste": 526019,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124740/JOELLE_BERGERON_home.html",
    "lien_site": "https://www.joelle-bergeron.eu/",
    "lien_twitter": "https://twitter.com/Jbergeronmep",
    "certifié": "Non",
    "followers": 81,
    "result": 0
  },
  {
    "num": 37,
    "id": 124760,
    "name": "Nicolas BAY",
    "first_name": "Nicolas",
    "last_name": "BAY",
    "gender": "H",
    "date_birth": "21 décembre 1977",
    "place_birth": "Saint-Germain-en-Laye",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Nord-Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "LISTE BLEU MARINE. OUI A LA FRANCE, NON A BRUXELLES (LFN)",
    "resultat_liste": "33,62",
    "nb_voix_liste": 914222,
    "nb_elus_liste": 5,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124760/NICOLAS_BAY_home.html",
    "lien_site": "http://nicolasbay.fr/",
    "lien_twitter": "https://twitter.com/NicolasBay_",
    "certifié": "Non",
    "followers": 40416,
    "result": 0
  },
  {
    "num": 38,
    "id": 124757,
    "name": "Steeve BRIOIS",
    "first_name": "Steeve",
    "last_name": "BRIOIS",
    "gender": "H",
    "date_birth": "28 novembre 1972",
    "place_birth": "Seclin",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Nord-Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "LISTE BLEU MARINE. OUI A LA FRANCE, NON A BRUXELLES (LFN)",
    "resultat_liste": "33,62",
    "nb_voix_liste": 914222,
    "nb_elus_liste": 5,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124757/STEEVE_BRIOIS_home.html",
    "lien_site": "Aucun",
    "lien_twitter": "https://twitter.com/steevebriois",
    "certifié": "Oui",
    "followers": 32047,
    "result": 0
  },
  {
    "num": 39,
    "id": 21331,
    "name": "Sylvie GODDYN",
    "first_name": "Sylvie",
    "last_name": "GODDYN",
    "gender": "F",
    "date_birth": "24 juin 1964",
    "place_birth": "Lille",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Nord-Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "LISTE BLEU MARINE. OUI A LA FRANCE, NON A BRUXELLES (LFN)",
    "resultat_liste": "33,62",
    "nb_voix_liste": 914222,
    "nb_elus_liste": 5,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/21331/SYLVIE_GODDYN_home.html",
    "lien_site": "Aucun",
    "lien_twitter": "https://twitter.com/Sylvie_Goddyn",
    "certifié": "Oui",
    "followers": 5392,
    "result": 0
  },
  {
    "num": 40,
    "id": 124758,
    "name": "Mylène TROSZCZYNSKI",
    "first_name": "Mylène",
    "last_name": "TROSZCZYNSKI",
    "gender": "F",
    "date_birth": "16 mai 1972",
    "place_birth": "Chauny",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Nord-Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "LISTE BLEU MARINE. OUI A LA FRANCE, NON A BRUXELLES (LFN)",
    "resultat_liste": "33,62",
    "nb_voix_liste": 914222,
    "nb_elus_liste": 5,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124758/MYLENE_TROSZCZYNSKI_home.html",
    "lien_site": "http://www.mylenetroszczynski.eu/",
    "lien_twitter": "https://twitter.com/Troszczynski_FN",
    "certifié": "Oui",
    "followers": 4020,
    "result": 0
  },
  {
    "num": 41,
    "id": 188718,
    "name": "Christelle LECHEVALIER",
    "first_name": "Christelle",
    "last_name": "LECHEVALIER",
    "gender": "F",
    "date_birth": "27 septembre 1968",
    "place_birth": "Falaise",
    "national_party": "Rassemblement national",
    "national_party_grp": 6,
    "circo": "Nord-Ouest",
    "eurodep_depuis": 2017,
    "longevity": 2,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "OUI",
    "eurogroup": "Groupe Europe des Nations et des Libertés",
    "liste_regionale": "LISTE BLEU MARINE. OUI A LA FRANCE, NON A BRUXELLES (LFN)",
    "resultat_liste": 914222,
    "nb_voix_liste": "33,62",
    "nb_elus_liste": 5,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/188718/CHRISTELLE_LECHEVALIER_home.html",
    "lien_site": "Aucun",
    "lien_twitter": "https://twitter.com/C_Lechevalier14",
    "certifié": "Non",
    "followers": 3018,
    "result": 0
  },
  {
    "num": 42,
    "id": 96883,
    "name": "Eva JOLY",
    "first_name": "Eva",
    "last_name": "JOLY",
    "gender": "F",
    "date_birth": "5 décembre 1943",
    "place_birth": "Oslo",
    "national_party": "Europe Écologie",
    "national_party_grp": 2,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe des Verts/Alliance libre européenne",
    "liste_regionale": "LISTE EUROPE ECOLOGIE (LVEC)",
    "resultat_liste": "9,68",
    "nb_voix_liste": 296766,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96883/EVA_JOLY_home.html",
    "lien_site": "http://europeangreens.eu/people/eva-joly",
    "lien_twitter": "https://twitter.com/EvaJoly",
    "certifié": "Non",
    "followers": 166880,
    "result": 0
  },
  {
    "num": 43,
    "id": 96740,
    "name": "Yannick JADOT",
    "first_name": "Yannick",
    "last_name": "JADOT",
    "gender": "H",
    "date_birth": "27 juillet 1967",
    "place_birth": "Clacy et Thierret",
    "national_party": "Europe Écologie",
    "national_party_grp": 2,
    "circo": "Ouest",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe des Verts/Alliance libre européenne",
    "liste_regionale": "LISTE EUROPE ECOLOGIE (LVEC)",
    "resultat_liste": "10,36",
    "nb_voix_liste": 282167,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96740/YANNICK_JADOT_home.html",
    "lien_site": "http://www.yannickjadot.fr/",
    "lien_twitter": "https://twitter.com/yjadot",
    "certifié": "Oui",
    "followers": 36008,
    "result": 0
  },
  {
    "num": 44,
    "id": 96868,
    "name": "Karima DELLI",
    "first_name": "Karima",
    "last_name": "DELLI",
    "gender": "F",
    "date_birth": "4 mars 1979",
    "place_birth": "Roubaix",
    "national_party": "Europe Écologie",
    "national_party_grp": 2,
    "circo": "Nord-Ouest",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe des Verts/Alliance libre européenne",
    "liste_regionale": "LISTE EUROPE ECOLOGIE (LVEC)",
    "resultat_liste": "7,16",
    "nb_voix_liste": 194595,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96868/KARIMA_DELLI_home.html",
    "lien_site": "http://www.karimadelli.com/",
    "lien_twitter": "https://twitter.com/KarimaDelli",
    "certifié": "Oui",
    "followers": 21318,
    "result": 0
  },
  {
    "num": 45,
    "id": 124693,
    "name": "Pascal DURAND",
    "first_name": "Pascal",
    "last_name": "DURAND",
    "gender": "H",
    "date_birth": "3 octobre 1960",
    "place_birth": "Montreuil-Sous-Bois",
    "national_party": "Europe Écologie",
    "national_party_grp": 2,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe des Verts/Alliance libre européenne",
    "liste_regionale": "LISTE EUROPE ECOLOGIE (LVEC)",
    "resultat_liste": "9,68",
    "nb_voix_liste": 296766,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124693/PASCAL_DURAND_home.html",
    "lien_site": "http://www.pascal-durand.eu/",
    "lien_twitter": "https://twitter.com/PDurandOfficiel",
    "certifié": "Oui",
    "followers": 14528,
    "result": 0
  },
  {
    "num": 46,
    "id": 96931,
    "name": "Maurice PONGA",
    "first_name": "Maurice",
    "last_name": "PONGA",
    "gender": "H",
    "date_birth": "5 juin 1947",
    "place_birth": "Kouaoua (Nouvelle-Calédonie)",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Outre-Mer",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE DES OUTRE-MER, AGIR EN EUROPE AVEC L'UMP (LUMP)",
    "resultat_liste": "26,7",
    "nb_voix_liste": 76168,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96931/MAURICE_PONGA_home.html",
    "lien_site": "http://mauriceponga.eu/",
    "lien_twitter": "https://twitter.com/mauriceponga",
    "certifié": "Non",
    "followers": 1517,
    "result": 0
  },
  {
    "num": 47,
    "id": 96849,
    "name": "Alain CADEC",
    "first_name": "Alain",
    "last_name": "CADEC",
    "gender": "H",
    "date_birth": "21 juin 1953",
    "place_birth": "Saint-Brieuc",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Ouest",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC ALAIN CADEC (LUMP)",
    "resultat_liste": "19,64",
    "nb_voix_liste": 535059,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96849/ALAIN_CADEC_home.html",
    "lien_site": "http://www.alain-cadec.org",
    "lien_twitter": "https://twitter.com/AlainCadec",
    "certifié": "Oui",
    "followers": 7326,
    "result": 0
  },
  {
    "num": 48,
    "id": 38596,
    "name": "Elisabeth MORIN-CHARTIER",
    "first_name": "Elisabeth",
    "last_name": "MORIN-CHARTIER",
    "gender": "F",
    "date_birth": "10 octobre 1947",
    "place_birth": "Ceaux-en-Couhé",
    "national_party": "Indépendant",
    "national_party_grp": 7,
    "circo": "Ouest",
    "eurodep_depuis": 2007,
    "longevity": 12,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC ALAIN CADEC (LUMP)",
    "resultat_liste": "19,64",
    "nb_voix_liste": 535059,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/38596/ELISABETH_MORIN-CHARTIER_home.html",
    "lien_site": "http://elisabeth-morinchartier.eu/",
    "lien_twitter": "http://twitter.com/emorinchartier",
    "certifié": "Oui",
    "followers": 6763,
    "result": 0
  },
  {
    "num": 49,
    "id": 124728,
    "name": "Marc JOULAUD",
    "first_name": "Marc",
    "last_name": "JOULAUD",
    "gender": "H",
    "date_birth": "3 septembre 1967",
    "place_birth": "Mayenne",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC ALAIN CADEC (LUMP)",
    "resultat_liste": "19,64",
    "nb_voix_liste": 535059,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124728/MARC_JOULAUD_home.html",
    "lien_site": "http://marcjoulaud.eu/",
    "lien_twitter": "https://twitter.com/MarcJoulaud",
    "certifié": "Oui",
    "followers": 2345,
    "result": 0
  },
  {
    "num": 50,
    "id": 72775,
    "name": "Rachida DATI",
    "first_name": "Rachida",
    "last_name": "DATI",
    "gender": "F",
    "date_birth": "27 novembre 1965",
    "place_birth": "Saint-Rémy",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC ALAIN LAMASSOURE (LUMP)",
    "resultat_liste": "21,79",
    "nb_voix_liste": 667991,
    "nb_elus_liste": 4,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/72775/RACHIDA_DATI_home.html",
    "lien_site": "https://www.rachida-dati.eu/",
    "lien_twitter": "http://twitter.com/datirachida",
    "certifié": "Oui",
    "followers": 133019,
    "result": 0
  },
  {
    "num": 51,
    "id": 190774,
    "name": "Geoffroy DIDIER",
    "first_name": "Geoffroy",
    "last_name": "DIDIER",
    "gender": "H",
    "date_birth": "12 avril 1976",
    "place_birth": "Boulogne-Billancourt",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2017,
    "longevity": 2,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "OUI",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC ALAIN LAMASSOURE (LUMP)",
    "resultat_liste": 667991,
    "nb_voix_liste": "21,79",
    "nb_elus_liste": 4,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/190774/GEOFFROY_DIDIER_home.html",
    "lien_site": "http://www.geoffroydidier.org/",
    "lien_twitter": "https://twitter.com/geoffroydidier",
    "certifié": "Oui",
    "followers": 29867,
    "result": 0
  },
  {
    "num": 52,
    "id": 96884,
    "name": "Philippe JUVIN",
    "first_name": "Philippe",
    "last_name": "JUVIN",
    "gender": "H",
    "date_birth": "1 février 1964",
    "place_birth": "Orléans",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC ALAIN LAMASSOURE (LUMP)",
    "resultat_liste": "21,79",
    "nb_voix_liste": 667991,
    "nb_elus_liste": 4,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96884/PHILIPPE_JUVIN_home.html",
    "lien_site": "http://www.philippejuvin.fr/",
    "lien_twitter": "https://twitter.com/philippejuvin",
    "certifié": "Oui",
    "followers": 7924,
    "result": 0
  },
  {
    "num": 53,
    "id": 1204,
    "name": "Alain LAMASSOURE",
    "first_name": "Alain",
    "last_name": "LAMASSOURE",
    "gender": "H",
    "date_birth": "10 février 1944",
    "place_birth": "Pau",
    "national_party": "Indépendant",
    "national_party_grp": 7,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 1999,
    "longevity": 20,
    "mandats_parl_eur": "1989-1993",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC ALAIN LAMASSOURE (LUMP)",
    "resultat_liste": "21,79",
    "nb_voix_liste": 667991,
    "nb_elus_liste": 4,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/1204/ALAIN_LAMASSOURE_home.html",
    "lien_site": "http://www.alainlamassoure.eu/",
    "lien_twitter": "https://twitter.com/ALamassoure",
    "certifié": "Oui",
    "followers": 6572,
    "result": 0
  },
  {
    "num": 54,
    "id": 5565,
    "name": "Brice HORTEFEUX",
    "first_name": "Brice",
    "last_name": "HORTEFEUX",
    "gender": "H",
    "date_birth": "11 mai 1958",
    "place_birth": "Neuilly-sur-Seine",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Massif-Central Centre",
    "eurodep_depuis": 2011,
    "longevity": 8,
    "mandats_parl_eur": "1999-2005",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC BRICE HORTEFEUX (LUMP)",
    "resultat_liste": "21,38",
    "nb_voix_liste": 314959,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/5565/BRICE_HORTEFEUX_home.html",
    "lien_site": "http://brice.hortefeux.free.fr/",
    "lien_twitter": "https://twitter.com/BriceHortefeux",
    "certifié": "Oui",
    "followers": 4541,
    "result": 0
  },
  {
    "num": 55,
    "id": 124732,
    "name": "Angélique DELAHAYE",
    "first_name": "Angélique",
    "last_name": "DELAHAYE",
    "gender": "F",
    "date_birth": "22 février 1963",
    "place_birth": "Lyon",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Massif-Central Centre",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC BRICE HORTEFEUX (LUMP)",
    "resultat_liste": "21,38",
    "nb_voix_liste": 314959,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124732/ANGELIQUE_DELAHAYE_home.html",
    "lien_site": "http://angelique-delahaye.eu/",
    "lien_twitter": "https://twitter.com/Delahaye_Europe",
    "certifié": "Oui",
    "followers": 3244,
    "result": 0
  },
  {
    "num": 56,
    "id": 4345,
    "name": "Tokia SAÏFI",
    "first_name": "Tokia",
    "last_name": "SAÏFI",
    "gender": "F",
    "date_birth": "11 juillet 1959",
    "place_birth": "Hautmont",
    "national_party": "Agir - La Droite constructive",
    "national_party_grp": 5,
    "circo": "Nord-Ouest",
    "eurodep_depuis": 2004,
    "longevity": 15,
    "mandats_parl_eur": "1999-2002",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC JÉRÔME LAVRILLEUX (LUMP)",
    "resultat_liste": "18,75",
    "nb_voix_liste": 509939,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/4345/TOKIA_SAIFI_home.html",
    "lien_site": "http://www.tokia-saifi.eu/",
    "lien_twitter": "http://twitter.com/TokiaSaifi",
    "certifié": "Oui",
    "followers": 4752,
    "result": 0
  },
  {
    "num": 57,
    "id": 124731,
    "name": "Jérôme LAVRILLEUX",
    "first_name": "Jérôme",
    "last_name": "LAVRILLEUX",
    "gender": "H",
    "date_birth": "19 septembre 1969",
    "place_birth": "Saint-Quentin",
    "national_party": "-",
    "national_party_grp": 5,
    "circo": "Nord-Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC JÉRÔME LAVRILLEUX (LUMP)",
    "resultat_liste": "18,75",
    "nb_voix_liste": 509939,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124731/JEROME_LAVRILLEUX_home.html",
    "lien_site": "http://www.jerome-lavrilleux.eu/",
    "lien_twitter": "https://twitter.com/lavrilleux_j?lang=fr",
    "certifié": "Oui",
    "followers": 696,
    "result": 0
  },
  {
    "num": 58,
    "id": 1179,
    "name": "Michèle ALLIOT-MARIE",
    "first_name": "Michèle",
    "last_name": "ALLIOT-MARIE",
    "gender": "F",
    "date_birth": "10 septembre 1946",
    "place_birth": "Villeneuve le Roi",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Sud-Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "1989-1993",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC MICHÈLE ALLIOT-MARIE (LUMP)",
    "resultat_liste": "18,52",
    "nb_voix_liste": 544551,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/1179/MICHELE_ALLIOT-MARIE_home.html",
    "lien_site": "Aucun",
    "lien_twitter": "https://twitter.com/malliotmarie",
    "certifié": "Oui",
    "followers": 27857,
    "result": 0
  },
  {
    "num": 59,
    "id": 108080,
    "name": "Franck PROUST",
    "first_name": "Franck",
    "last_name": "PROUST",
    "gender": "H",
    "date_birth": "2 mai 1963",
    "place_birth": "Poitiers",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Sud-Ouest",
    "eurodep_depuis": 2011,
    "longevity": 8,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC MICHÈLE ALLIOT-MARIE (LUMP)",
    "resultat_liste": "18,52",
    "nb_voix_liste": 544551,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/108080/FRANCK_PROUST_home.html",
    "lien_site": "http://www.franckproust.com/",
    "lien_twitter": "https://twitter.com/franckproust",
    "certifié": "Oui",
    "followers": 6063,
    "result": 0
  },
  {
    "num": 60,
    "id": 72779,
    "name": "Nadine MORANO",
    "first_name": "Nadine",
    "last_name": "MORANO",
    "gender": "F",
    "date_birth": "6 novembre 1963",
    "place_birth": "Nancy",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC NADINE MORANO (LUMP)",
    "resultat_liste": "22,72",
    "nb_voix_liste": 551809,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/72779/NADINE_MORANO_home.html",
    "lien_site": "http://www.nadinemorano.fr/",
    "lien_twitter": "https://twitter.com/nadine__morano",
    "certifié": "Oui",
    "followers": 202557,
    "result": 0
  },
  {
    "num": 61,
    "id": 96747,
    "name": "Arnaud DANJEAN",
    "first_name": "Arnaud",
    "last_name": "DANJEAN",
    "gender": "H",
    "date_birth": "11 février 1971",
    "place_birth": "Louhans",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Est",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC NADINE MORANO (LUMP)",
    "resultat_liste": "22,72",
    "nb_voix_liste": 551809,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96747/ARNAUD_DANJEAN_home.html",
    "lien_site": "http://www.arnaud-danjean.fr/",
    "lien_twitter": "https://twitter.com/ArnaudDanjean",
    "certifié": "Oui",
    "followers": 14063,
    "result": 0
  },
  {
    "num": 62,
    "id": 24594,
    "name": "Anne SANDER",
    "first_name": "Anne",
    "last_name": "SANDER",
    "gender": "F",
    "date_birth": "1 octobre 1973",
    "place_birth": "Haguenau",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC NADINE MORANO (LUMP)",
    "resultat_liste": "22,72",
    "nb_voix_liste": 551809,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/24594/ANNE_SANDER_home.html",
    "lien_site": "http://www.annesander.eu/fr/",
    "lien_twitter": "https://twitter.com/ASanderMEP",
    "certifié": "Oui",
    "followers": 1770,
    "result": 0
  },
  {
    "num": 63,
    "id": 124729,
    "name": "Renaud MUSELIER",
    "first_name": "Renaud",
    "last_name": "MUSELIER",
    "gender": "H",
    "date_birth": "6 mai 1959",
    "place_birth": "Marseille",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Sud-Est",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC RENAUD MUSELIER (LUMP)",
    "resultat_liste": "22,4",
    "nb_voix_liste": 743343,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124729/RENAUD_MUSELIER_home.html",
    "lien_site": "http://www.renaudmuselier.fr/",
    "lien_twitter": "https://twitter.com/RenaudMuselier",
    "certifié": "Oui",
    "followers": 16957,
    "result": 0
  },
  {
    "num": 64,
    "id": 97296,
    "name": "Michel DANTIN",
    "first_name": "Michel",
    "last_name": "DANTIN",
    "gender": "H",
    "date_birth": "15 janvier 1960",
    "place_birth": "Lyon",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Sud-Est",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC RENAUD MUSELIER (LUMP)",
    "resultat_liste": "22,4",
    "nb_voix_liste": 743343,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/97296/MICHEL_DANTIN_home.html",
    "lien_site": "http://www.micheldantin.net/",
    "lien_twitter": "https://twitter.com/MichelDANTIN",
    "certifié": "Oui",
    "followers": 10048,
    "result": 0
  },
  {
    "num": 65,
    "id": 2025,
    "name": "Françoise GROSSETÊTE",
    "first_name": "Françoise",
    "last_name": "GROSSETÊTE",
    "gender": "F",
    "date_birth": "17 mai 1946",
    "place_birth": "Lyon",
    "national_party": "Les Républicains",
    "national_party_grp": 5,
    "circo": "Sud-Est",
    "eurodep_depuis": 1994,
    "longevity": 25,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe du Parti populaire européen (Démocrates-Chrétiens)",
    "liste_regionale": "POUR LA FRANCE, AGIR EN EUROPE AVEC RENAUD MUSELIER (LUMP)",
    "resultat_liste": "22,4",
    "nb_voix_liste": 743343,
    "nb_elus_liste": 3,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/2025/FRANCOISE_GROSSETETE_home.html",
    "lien_site": "http://www.francoise-grossetete.eu/",
    "lien_twitter": "https://twitter.com/GrosseteteF",
    "certifié": "Oui",
    "followers": 7927,
    "result": 0
  },
  {
    "num": 66,
    "id": 96735,
    "name": "Patrick LE HYARIC",
    "first_name": "Patrick",
    "last_name": "LE HYARIC",
    "gender": "H",
    "date_birth": "4 février 1957",
    "place_birth": "Orléans",
    "national_party": "Front de Gauche",
    "national_party_grp": 1,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe confédéral de la Gauche unitaire européenne/Gauche verte nordique",
    "liste_regionale": "STOP A L'EUROPE DE LA FINANCE-L'HUMAIN D'ABORD ! FRONT DE GAUCHE (LFG)",
    "resultat_liste": "6,48",
    "nb_voix_liste": 198534,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96735/PATRICK_LE+HYARIC_home.html",
    "lien_site": "http://patricklehyaric.net/",
    "lien_twitter": "http://twitter.com/PatrickLeHyaric",
    "certifié": "Oui",
    "followers": 10950,
    "result": 0
  },
  {
    "num": 67,
    "id": 124773,
    "name": "Jean ARTHUIS",
    "first_name": "Jean",
    "last_name": "ARTHUIS",
    "gender": "H",
    "date_birth": "7 octobre 1944",
    "place_birth": "Saint-Martin du Bois",
    "national_party": "Union des Démocrates et Indépendants",
    "national_party_grp": 4,
    "circo": "Ouest",
    "eurodep_depuis": 2014,
    "longevity": 5,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Alliance des démocrates et des libéraux pour l'Europe",
    "liste_regionale": "UDI MODEM LES EUROPEENS. LISTE SOUTENUE PAR FRANÇOIS BAYROU ET JEAN-LOUIS BORLOO (LUC)",
    "resultat_liste": "12,29",
    "nb_voix_liste": 334963,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/124773/JEAN_ARTHUIS_home.html",
    "lien_site": "http://www.jean-arthuis.eu/",
    "lien_twitter": "https://twitter.com/JeanArthuis",
    "certifié": "Oui",
    "followers": 22181,
    "result": 0
  },
  {
    "num": 68,
    "id": 28206,
    "name": "Jean-Marie CAVADA",
    "first_name": "Jean-Marie",
    "last_name": "CAVADA",
    "gender": "H",
    "date_birth": "24 février 1940",
    "place_birth": "Epinal",
    "national_party": "Génération Citoyens",
    "national_party_grp": 7,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2004,
    "longevity": 15,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Alliance des démocrates et des libéraux pour l'Europe",
    "liste_regionale": "UDI MODEM LES EUROPEENS. LISTE SOUTENUE PAR FRANÇOIS BAYROU ET JEAN-LOUIS BORLOO (LUC)",
    "resultat_liste": "11,99",
    "nb_voix_liste": 367513,
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/28206/JEAN-MARIE_CAVADA_home.html",
    "lien_site": "http://www.jeanmariecavada.eu",
    "lien_twitter": "https://twitter.com/JeanMarieCAVADA",
    "certifié": "Oui",
    "followers": 11999,
    "result": 0
  },
  {
    "num": 69,
    "id": 28208,
    "name": "Nathalie GRIESBECK",
    "first_name": "Nathalie",
    "last_name": "GRIESBECK",
    "gender": "F",
    "date_birth": "24 mai 1956",
    "place_birth": "Metz",
    "national_party": "Mouvement Démocrate",
    "national_party_grp": 4,
    "circo": "Est",
    "eurodep_depuis": 2004,
    "longevity": 15,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Alliance des démocrates et des libéraux pour l'Europe",
    "liste_regionale": "UDI MODEM LES EUROPEENS. LISTE SOUTENUE PAR FRANÇOIS BAYROU ET JEAN-LOUIS BORLOO (LUC)",
    "resultat_liste": "9,19",
    "nb_voix_liste": 223280,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/28208/NATHALIE_GRIESBECK_home.html",
    "lien_site": "http://www.nathalie-griesbeck.fr/",
    "lien_twitter": "https://twitter.com/Nat_GRIESBECK",
    "certifié": "Oui",
    "followers": 6861,
    "result": 0
  },
  {
    "num": 70,
    "id": 97022,
    "name": "Robert ROCHEFORT",
    "first_name": "Robert",
    "last_name": "ROCHEFORT",
    "gender": "H",
    "date_birth": "19 septembre 1955",
    "place_birth": "",
    "national_party": "Mouvement Démocrate",
    "national_party_grp": 4,
    "circo": "Sud-Ouest",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Alliance des démocrates et des libéraux pour l'Europe",
    "liste_regionale": "UDI MODEM LES EUROPEENS. LISTE SOUTENUE PAR FRANÇOIS BAYROU ET JEAN-LOUIS BORLOO (LUC)",
    "resultat_liste": "8,6",
    "nb_voix_liste": 253069,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/97022/ROBERT_ROCHEFORT_home.html",
    "lien_site": "http://www.robertrochefort.eu/",
    "lien_twitter": "http://twitter.com/robertrochefort",
    "certifié": "Oui",
    "followers": 6241,
    "result": 0
  },
  {
    "num": 71,
    "id": 188254,
    "name": "Patricia LALONDE",
    "first_name": "Patricia",
    "last_name": "LALONDE",
    "gender": "F",
    "date_birth": "28 août 1952",
    "place_birth": "Ares",
    "national_party": "Union des Démocrates et Indépendants",
    "national_party_grp": 4,
    "circo": "Ile-de-France et Français HF",
    "eurodep_depuis": 2017,
    "longevity": 2,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "OUI",
    "eurogroup": "Groupe Alliance des démocrates et des libéraux pour l'Europe",
    "liste_regionale": "UDI MODEM LES EUROPEENS. LISTE SOUTENUE PAR FRANÇOIS BAYROU ET JEAN-LOUIS BORLOO (LUC)",
    "resultat_liste": 367513,
    "nb_voix_liste": "11,99",
    "nb_elus_liste": 2,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/188254/PATRICIA_LALONDE_home.html",
    "lien_site": "Aucun",
    "lien_twitter": "https://twitter.com/patricialalond2",
    "certifié": "Oui",
    "followers": 582,
    "result": 0
  },
  {
    "num": 72,
    "id": 96885,
    "name": "Dominique RIQUET",
    "first_name": "Dominique",
    "last_name": "RIQUET",
    "gender": "H",
    "date_birth": "18 septembre 1946",
    "place_birth": "Valenciennes",
    "national_party": "Mouvement Radical Social-Libéral",
    "national_party_grp": 3,
    "circo": "Nord-Ouest",
    "eurodep_depuis": 2009,
    "longevity": 10,
    "mandats_parl_eur": "Aucun",
    "succession_cours_mandat": "NON",
    "eurogroup": "Groupe Alliance des démocrates et des libéraux pour l'Europe",
    "liste_regionale": "UDI MODEM LES EUROPÉENS. LISTE SOUTENUE PAR FRANÇOIS BAYROU ET JEAN-LOUIS BORLOO (LUC)",
    "resultat_liste": "9,38",
    "nb_voix_liste": 255108,
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/96885/DOMINIQUE_RIQUET_home.html",
    "lien_site": "http://driquet.com/",
    "lien_twitter": "https://twitter.com/DominiqueRiquet",
    "certifié": "Oui",
    "followers": 3879,
    "result": 0
  },
  {
    "num": 73,
    "id": 4338,
    "name": "Thierry CORNILLET",
    "first_name": "Thierry",
    "last_name": "CORNILLET",
    "gender": "H",
    "date_birth": "23 juillet 1951",
    "place_birth": "Montelimar",
    "national_party": "Mouvement Radical",
    "national_party_grp": 3,
    "circo": "Sud-Ouest",
    "eurodep_depuis": 2017,
    "longevity": 2,
    "mandats_parl_eur": "1999-2009",
    "succession_cours_mandat": "OUI",
    "eurogroup": "Groupe Alliance des démocrates et des libéraux pour l'Europe",
    "liste_regionale": "UDI MODEM LES EUROPÉENS. LISTE SOUTENUE PAR FRANÇOIS BAYROU ET JEAN-LOUIS BORLOO (LUC)",
    "resultat_liste": 280091,
    "nb_voix_liste": "8,44",
    "nb_elus_liste": 1,
    "lien_europarl": "http://www.europarl.europa.eu/meps/fr/4338/THIERRY_CORNILLET_home.html",
    "lien_site": "Aucun",
    "lien_twitter": "https://twitter.com/TCornillet",
    "certifié": "Non",
    "followers": 1067,
    "result": 0
  }
];
